name: Build Vue+Vite Project
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
 
    - name: Cache Node.js modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: npm install
 
    - name: Build project
      run: npm run build
 
    - name: Configure HTML
      # 假设你有一个脚本来配置HTML，例如自动插入生成的JS和CSS文件
      run: |
        ./configure-html.sh
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist